plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.pawsulin'
version = '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

// Disable bootJar for root project as it has no source code
// and it's redundant with the :backend project
bootJar {
    enabled = false
}

jar {
    enabled = false
}
